### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kurokuno** [LousyLynx/Infinity-Storage#11]
crash

http://pastebin.com/AWSkpPAL

**Comment by BSFishy** [comment]
1) What version of Minecraft Forge are you using? Infinity Storage is compiled with 12.18.1.2077. Make sure you have that version, or later.

2) What would be the steps to reproduce? If I don't know what to fix, I can't fix it.

**Comment by raoulvdberge** [comment]
You uploaded the non-obfuscated version from Bintray on Curse... You have to upload the output file you get from `gradle build`.

**Comment by kurokuno** [comment]
raoulvdberge explained the issue perfectly

**Comment by BSFishy** [comment]
Thank you raoulvdberge!
